name: ByteEconomy
main: tech.ccat.byte.BytePlugin
version: 1.0.0
api-version: 1.21
softdepend: [Vault]
commands:
  byte:
    description: Manage byte currency
    usage: /byte [add/set/take/reload]
  coin:
    description: Manage coin currency
    usage: /coin [add/set/take]
  point:
    description: Manage point currency
    usage: /point [add/set/take]